✨ 프로그램 목록 App Icon 추가
LemonScone/check-it-out pull request #28
Opened 2022-05-20 06:53 UTC by padosum

- extract-file-icon 설치
- icon이 저장되는 경로: /public/assets/images
- icon이 이미 저장되었는지 체크 후 저장
- ProgramTable 컴포넌트에서 bundleId 이름으로 저장된 이미지 로드

2022-05-23 12:46 UTC, the1020 requested changes
빠른 시일 내에 수정해주세요

2022-05-23 12:46 UTC, the1020 commented on public/electron.js
> +    const bundleId = window.owner.bundleId.replace(/\./g, '-');
window.owner.bundleId는 macOS에서만 받아올 수 있어서 window.owner.name을 사용해야 합니다.

2022-05-23 12:46 UTC, the1020 commented on public/utils/icon.js
> +  const pathToAsset = path.join(__dirname, `../assets/images/${appName}.png`);
`/assets/images` 경로가 없으면 파일이 저장되지 않습니다.
=> 해당 경로가 있는지 확인해서 없으면 만들어주고 저장소에도 해당 경로 올려두기

2022-05-23 12:46 UTC, the1020 commented on src/components/ProgramTable.js
> +                          src={`../../assets/images/${row.bundleId}.png`}
이미지 경로가 없는 경우 대체 이미지 넣기

2022-05-23 12:46 UTC, the1020 commented on src/components/ProgramTable.js
>        format(startDate, 'HH:mm'),
date 포맷을 `HH:mm:ss`로 수정하기

2022-05-23 13:18 UTC, padosum commented on public/utils/icon.js
> +  const pathToAsset = path.join(__dirname, `../assets/images/${appName}.png`);
`.gitignore` 파일에 해당 경로 추가하기

2022-05-23 23:51 UTC, padosum commented on src/components/ProgramTable.js
> +                          src={`../../assets/images/${row.bundleId}.png`}
Name column에 아이콘 넣기

2022-05-24 03:02 UTC, padosum commented on public/utils/icon.js
> +  const pathToAsset = path.join(__dirname, `../assets/images/${appName}.png`);
> `/assets/images` 경로가 없으면 파일이 저장되지 않습니다. => 해당 경로가 있는지 확인해서 없으면 만들어주고 저장소에도 해당 경로 올려두기

[이미지](https://freesvg.org/ios-7-icon-template)

2022-05-24 03:29 UTC, padosum commented on src/components/ProgramTable.js
> +                          src={`../../assets/images/${row.bundleId}.png`}
> 이미지 경로가 없는 경우 대체 이미지 넣기

[이미지](https://freesvg.org/ios-7-icon-template)

2022-05-24 03:40 UTC, padosum commented on public/utils/icon.js
> +  const pathToAsset = path.join(__dirname, `../assets/images/${appName}.png`);
> `/assets/images` 경로가 없으면 파일이 저장되지 않습니다. => 해당 경로가 있는지 확인해서 없으면 만들어주고 저장소에도 해당 경로 올려두기

그냥 저장소에 해당 경로를 추가해두었음!

2022-05-24 07:20 UTC, merged