✨ electron-store 적용, TODAY 버튼 생성
LemonScone/check-it-out pull request #29
Opened 2022-05-25 13:09 UTC by the1020

- electron-store를 이용하여 데이터 관리하기
- 화살표 버튼(`<`, `>`)으로 날짜 이동하여 해당 날짜에 기록된 데이터 가져오기
- 다른 프로그램으로 포커스가 이동한 경우(= 활성화된 프로그램이 변경된 경우)를 확인할 조건 변경 : app.id와 app.title이 다르면 새로운 프로그램으로 간주
  - 예) Chrome을 실행중이어도 탭을 이동하면 새로운 프로그램으로 간주하여 해당 active-win 정보를 저장
- (1)_앱이 종료되거나_ (2)_추적 시작/종료 버튼을 클릭한 경우_ 현재 활성화된 프로그램의 종료 시간과 활성 시간을 계산해 저장소에 업데이트 처리
- 오늘 기록된 데이터를 가져올 `TODAY` 버튼 생성
- 앱 최초 실행 시 저장소에 있는 데이터 가져오기

2022-05-26 12:13 UTC, padosum requested changes

2022-05-26 12:13 UTC, padosum commented on public/utils/dateFormat.js
> +    xHours: (count) => `${count}hour`,
#15
`*h *m *s` 형식으로 하면 조금 더 짧아서 가독성이 좋을 것 같아요

2022-05-26 12:13 UTC, padosum commented on src/components/Toolbar.js
> +    <Button variant="contained" onClick={handleTodayButtonClick} color={'success'}>
`<Button>` 컴포넌트에 margin이 약간 있으면 더 보기 좋을 것 같아요
```jsx
<Button variant="contained" onClick={handleTodayButtonClick} color={'success'} sx={{ ml: 1 }}>
```

2022-05-26 12:13 UTC, padosum commented on public/electron.js
> +    trackWindowStore.getStore();
후속 코드에서 `this.#trackWindows`를 업데이트 하고 있는데,
매번 `ACTIVE_WINDOW` 메시지를 전달받을 때마다 
`getStore()`로 값을 가져오지 않아도 괜찮으지 않을까요?

2022-05-26 12:13 UTC, padosum commented on public/store/TrackWindowStore.js
> +  setStore = () => {
`setStore` 함수를 필요한 부분마다 호출하고 있는데
~~API에 있는 [onDidChange](https://github.com/sindresorhus/electron-store#ondidchangekey-callback) 메서드를 사용해서 이벤트 발생시에 해당 함수를 넣어놓는 것은 어떨까요?~~

아니면,
어차피 모든 데이터 흐름은 `#store` 등 클래스 필드를 사용하고 있으니 `STOP_ACTIVE_WINDOW` 메시지가 발생한 경우에만 
`setStore`를 사용하는 것은 어떨까요?

기준을 같이 정해보면 좋을듯합니다

2022-05-27 08:57 UTC, the1020 commented on public/store/TrackWindowStore.js
> +  setStore = () => {
앱이 동작하는 동안 `#trackWindows`로만 데이터 관리하고 앱이 종료되거나 버튼 이벤트로 추적을 종료할 경우에만 `electron-store의 저장소를 업데이트하도록 하였습니다.

2022-05-27 08:58 UTC, the1020 commented on public/electron.js
> +    trackWindowStore.getStore();
앱이 최초 실행될 때에만 `getStore()`로 저장소의 데이터를 요청하고 앱이 실행되는 동안에는 클래스 필드로만 데이터를 관리하도록 하였습니다.

2022-05-27 08:58 UTC, the1020 commented on public/utils/dateFormat.js
> +    xHours: (count) => `${count}hour`,
수정하였습니다.

2022-05-27 08:58 UTC, the1020 commented on src/components/Toolbar.js
> +    <Button variant="contained" onClick={handleTodayButtonClick} color={'success'}>
수정하였습니다.

2022-05-27 08:58 UTC, merged